### PR TITLE
[Feature] DND-2: Deploy pipeline

### PR DESCRIPTION
**Pull request by franco-marini**
# [DND-2: CI CD Pipeline](https://dumb-and-dangerous.atlassian.net/browse/DND-2)

## Type of change

- Feature (new feature of the server/application)

## Description

- Deploy pipeline to vercel
- Run check lint and types

### CODE REVIEW

**Comment by franco-marini** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>cd3d96b</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://dnd-qtrvlmgqt-dumb-and-dangerous.vercel.app'>https://dnd-qtrvlmgqt-dumb-and-dangerous.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/dumb-and-dangerous/dnd-app/Ghf5qBVLJrQ8nRMCmRx5V3xYEtWb'>https://vercel.com/dumb-and-dangerous/dnd-app/Ghf5qBVLJrQ8nRMCmRx5V3xYEtWb</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/dumb-and-dangerous/dnd-app/actions/runs/5919118478)

**Comment by franco-marini** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>8c5ee6f</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://dnd-oeifvfu48-dumb-and-dangerous.vercel.app'>https://dnd-oeifvfu48-dumb-and-dangerous.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/dumb-and-dangerous/dnd-app/52QjrE88AyRU9BxTvZAMMBMqmWHw'>https://vercel.com/dumb-and-dangerous/dnd-app/52QjrE88AyRU9BxTvZAMMBMqmWHw</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/dumb-and-dangerous/dnd-app/actions/runs/5919177449)

**Review by juanvaldano — APPROVED** [review]
I don't understand it, but it looks good 👍

**Comment by franco-marini** [comment]
This pull request has been deployed to Vercel.

<table>
<tr>
<td><strong>Latest commit:</strong></td>
<td><code>1cd7102</code></td>
</tr>
<tr>
<td><strong>✅ Preview:</strong></td>
<td><a href='https://dnd-fg3lrj12h-dumb-and-dangerous.vercel.app'>https://dnd-fg3lrj12h-dumb-and-dangerous.vercel.app</a></td>
</tr>
<tr>
<td><strong>🔍 Inspect:</strong></td>
<td><a href='https://vercel.com/dumb-and-dangerous/dnd-app/FxtACJYUKos2ZfFo1gFrgPjVJCWA'>https://vercel.com/dumb-and-dangerous/dnd-app/FxtACJYUKos2ZfFo1gFrgPjVJCWA</a></td>
</tr>
</table>

[View Workflow Logs](https://github.com/dumb-and-dangerous/dnd-app/actions/runs/5919199562)

**Pull request merged**
